#!/bin/bash
set -e

if [ "$#" == "0" ]; then
  echo "Usage: $0 dir1 dir2 dir3 ... dirN" >&2
  exit 1
fi

cat <<__EOF
# Spreadsheet API

Once you've successfully added defi-google-sheets to your spreadsheet, you'll have access to the following functions:

__EOF

while (( "$#" )); do
  # XXX use jsdoc
  shift
done
