#!/bin/bash
set -e

if [ "$#" -ne "1" ]; then
  echo "Usage: $0 input.j2" >&2
  exit 1
fi

if ! command -v jinja &> /dev/null; then
  echo "You must install jinja CLI to build documentation" >&2
  echo "Try running: pip install jinja-cli" >&2
  exit 1
fi

documentation_schema=$(mktemp)
cat <<'__EOF' > $documentation_schema
{
  common: .,
  bc: $bc[0],
  es: {
    accounts: $esAccount[0],
    common: $esCommon[0],
    gasTracker: $esGasTracker[0],
    stats: $esStats[0],
    blocks: $esBlocks[0],
    gethParityProxy: $esGethParityProxy[0],
    tokens: $esTokens[0],
    contracts: $esContracts[0],
    logs: $esLogs[0],
    transactions: $esTransactions[0],
  },
}
__EOF

input_json=$(mktemp)
jq -f $documentation_schema \
  --slurpfile bc .external_docs_cache/beaconchaindocs.json \
  --slurpfile esCommon templates/etherscan/common.json \
  --slurpfile esAccount templates/etherscan/"Accounts.postman_collection.json" \
  --slurpfile esGasTracker templates/etherscan/"Gas Tracker.postman_collection.json" \
  --slurpfile esStats templates/etherscan/"Stats.postman_collection.json" \
  --slurpfile esBlocks templates/etherscan/"Blocks.postman_collection.json" \
  --slurpfile esGethParityProxy templates/etherscan/"Geth-Parity Proxy.postman_collection.json" \
  --slurpfile esTokens templates/etherscan/"Tokens.postman_collection.json" \
  --slurpfile esContracts templates/etherscan/"Contracts.postman_collection.json" \
  --slurpfile esLogs templates/etherscan/"Logs.postman_collection.json" \
  --slurpfile esTransactions templates/etherscan/"Transactions.postman_collection.json" \
  templates/common.json > $input_json

output_file=`echo -n $1 | sed -e 's/\.ts\.j2/.generated.ts/g'`
jinja -d $input_json -o $output_file -f json $1

rm -f $documentation_schema $input_json
